"""Compute Inter-Rater Reliability (IRR) for the human-evaluation v3 sample.

Reads:
  outputs/human_eval/v3/human_eval_sample.json
      Gold mapping: per-item judge_winner, per_provider_winners, aa_delta,
      stratum, n_agree, axis, target_pole, base_is_response_a.
  outputs/human_eval/v3/studio_export.json
      LLARS Studio export (scenario 442 _final): per (rater, item) A/B/tie.

Emits:
  outputs/human_eval/v3/irr_summary.json
      Machine-readable summary of every metric computed below.
  paper/tables/tab_irr_headline.tex
  paper/tables/tab_irr_stratum.tex
  paper/tables/tab_irr_axis.tex
  paper/tables/tab_irr_nagree.tex
      Auto-generated LaTeX tables consumed by §6.3 and Appendix A.

Reliability raters considered:
  Four primary humans (RaterA, RaterB, RaterD, RaterC)
  and the three provider judges (Magistral, Nano, GPT-OSS-120B). All
  four humans annotated essentially the full 124-item sample
  (coverage 90--100%); 110 items were rated by all four and form the
  joint-subset for Fleiss's κ and human-majority statistics.

Implements Cohen's kappa, Fleiss's kappa, and Pearson r in pure Python
without scipy. Run from repo root with:
  .venv/bin/python scripts/compute_irr.py
"""

from __future__ import annotations

import json
import re
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GOLD_PATH = ROOT / "outputs/human_eval/v3/human_eval_sample.json"
STUDIO_PATH = ROOT / "outputs/human_eval/v3/studio_export.json"
SUMMARY_PATH = ROOT / "outputs/human_eval/v3/irr_summary.json"
TABLES_DIR = ROOT / "paper/tables"

PRIMARY_RATERS = ["RaterA", "RaterB", "RaterD", "RaterC"]
# Paper-side anonymisation: studio-account names get mapped to Rater 1/2/3/4 in
# all rendered LaTeX tables (App.\ ref{app:irr-detail} documents this). The
# (RaterA, RaterB) ordering is preserved across the 3→4 rater extension so
# that existing per-item references (e.g. Item 38, where Rater~2 = RaterB) stay
# valid; RaterD was added as Rater~3 in chronological annotation order.
RATER_ALIAS = {r: f"Rater {i+1}" for i, r in enumerate(PRIMARY_RATERS)}


def anon(name: str) -> str:
    """Render-time anonymisation for studio-rater account names."""
    return RATER_ALIAS.get(name, name)

JUDGES = [
    ("Mistral", "cluster_mistral:mistralai/Magistral-Small-2509"),
    ("Nano", "openai:gpt-5.4-nano@high"),
    ("GPT-OSS", "ionos:openai/gpt-oss-120b@high"),
]
JKEY = dict(JUDGES)
CATS3 = ["base", "steered", "tie"]
CAT_IDX = {c: i for i, c in enumerate(CATS3)}

TABLE_HEADER = (
    "% auto-generated by scripts/compute_irr.py — do not edit by hand\n"
)


# ----------------------------------------------------------------------------- IO
def load_data() -> tuple[dict[int, dict], dict[str, dict[int, str]]]:
    """Return (gold_by_item_no, per_user_label_3cat).

    Drops raters with fewer than 5 ratings except as noted in summary."""
    with GOLD_PATH.open() as f:
        gold = json.load(f)
    g_by_no = {int(r["item_no"]): r for r in gold}

    with STUDIO_PATH.open() as f:
        sc = json.load(f)

    per_user: dict[str, dict[int, str]] = defaultdict(dict)
    for r in sc["results"]:
        m = re.match(r"Item\s+(\d+)", r["item_subject"])
        if m is None:
            continue
        no = int(m.group(1))
        if no not in g_by_no:
            continue
        g = g_by_no[no]
        base_is_a = bool(g["base_is_response_a"])
        h = r["choice"]
        if h == "A":
            lab = "base" if base_is_a else "steered"
        elif h == "B":
            lab = "steered" if base_is_a else "base"
        else:
            lab = "tie"
        # Studio may contain multiple votes from the same user (re-rate);
        # keep latest by timestamp.
        prev_ts = per_user[r["username"]].get(("_ts", no))
        if prev_ts is None or r["updated_at"] >= prev_ts:
            per_user[r["username"]][no] = lab
            per_user[r["username"]][("_ts", no)] = r["updated_at"]

    # strip ts markers
    cleaned = {
        u: {k: v for k, v in d.items() if not (isinstance(k, tuple) and k[0] == "_ts")}
        for u, d in per_user.items()
    }
    return g_by_no, cleaned


# ----------------------------------------------------------------------------- metrics
def cohen_kappa(pairs: list[tuple[str, str]], cats: list[str]) -> tuple[float, float]:
    """Return (kappa, agreement). NaN when undefined (n<2)."""
    n = len(pairs)
    if n < 1:
        return float("nan"), float("nan")
    obs = sum(1 for a, b in pairs if a == b) / n
    if n < 2:
        # Single observation -- kappa is not defined.
        return float("nan"), obs
    p1 = {c: sum(1 for a, _ in pairs if a == c) / n for c in cats}
    p2 = {c: sum(1 for _, b in pairs if b == c) / n for c in cats}
    pe = sum(p1[c] * p2[c] for c in cats)
    kappa = (obs - pe) / (1 - pe) if pe < 1 else float("nan")
    return kappa, obs


def fleiss_kappa(rows: list[list[int]], cats: list[str]) -> float:
    """Rows are per-item category counts (one row per item, len(cats) columns).
    Each row sums to the same number of raters R."""
    N = len(rows)
    if N < 2:
        return float("nan")
    R = sum(rows[0])
    if R < 2:
        return float("nan")
    p = {i: sum(r[i] for r in rows) / (N * R) for i in range(len(cats))}
    Pe = sum(p[i] ** 2 for i in p)
    Pbar = sum(sum(c * (c - 1) for c in row) / (R * (R - 1)) for row in rows) / N
    return (Pbar - Pe) / (1 - Pe) if Pe < 1 else float("nan")


def pearson(xs: list[float], ys: list[float]) -> float:
    n = len(xs)
    if n < 2:
        return float("nan")
    mx, my = sum(xs) / n, sum(ys) / n
    sxy = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    sxx = sum((x - mx) ** 2 for x in xs)
    syy = sum((y - my) ** 2 for y in ys)
    return sxy / ((sxx * syy) ** 0.5) if sxx > 0 and syy > 0 else float("nan")


def majority(votes: list[str]) -> str:
    c = Counter(votes).most_common()
    if len(c) >= 2 and c[0][1] == c[1][1]:
        return "tie"
    return c[0][0]


# ----------------------------------------------------------------------------- aggregations
def per_rater_vs_ensemble(per_user: dict, g_by_no: dict) -> dict:
    out: dict[str, dict] = {}
    for r in PRIMARY_RATERS:
        items = per_user.get(r, {})
        pairs = [(items[n], g_by_no[n]["judge_winner"]) for n in items]
        k, a = cohen_kappa(pairs, CATS3)
        # pearson on continuous Δaa
        code = {"steered": 1.0, "base": -1.0, "tie": 0.0}
        xs = [code[items[n]] for n in items]
        ys = [g_by_no[n]["aa_delta"] for n in items]
        out[r] = {
            "n": len(items),
            "kappa_vs_ensemble": k,
            "agreement_vs_ensemble": a,
            "pearson_r_vs_delta_aa": pearson(xs, ys),
        }
    return out


def per_rater_vs_each_judge(per_user: dict, g_by_no: dict) -> dict:
    out: dict[str, dict] = {}
    for r in PRIMARY_RATERS:
        items = per_user.get(r, {})
        row = {"n": len(items)}
        for jname, jkey in JUDGES:
            pairs = []
            for n in items:
                jv = g_by_no[n]["per_provider_winners"].get(jkey)
                if jv is None:
                    continue
                pairs.append((items[n], jv))
            k, a = cohen_kappa(pairs, CATS3)
            row[jname] = {"kappa": k, "agreement": a, "n": len(pairs)}
        out[r] = row
    return out


def inter_human_pairwise(per_user: dict) -> dict:
    out = {}
    rs = PRIMARY_RATERS
    for i, u1 in enumerate(rs):
        for u2 in rs[i + 1 :]:
            common = set(per_user[u1]) & set(per_user[u2])
            pairs = [(per_user[u1][n], per_user[u2][n]) for n in common]
            k, a = cohen_kappa(pairs, CATS3)
            out[f"{u1} vs {u2}"] = {"n": len(pairs), "kappa": k, "agreement": a}
    return out


def fleiss_block(per_user: dict, g_by_no: dict) -> dict:
    common = set.intersection(*[set(per_user[r]) for r in PRIMARY_RATERS])
    common = sorted(common)
    rows_h = []
    for n in common:
        cnt = [0, 0, 0]
        for r in PRIMARY_RATERS:
            cnt[CAT_IDX[per_user[r][n]]] += 1
        rows_h.append(cnt)
    rows_j = []
    for n in common:
        g = g_by_no[n]
        cnt = [0, 0, 0]
        ok = True
        for _, jk in JUDGES:
            v = g["per_provider_winners"].get(jk)
            if v is None:
                ok = False
                break
            cnt[CAT_IDX[v]] += 1
        if ok:
            rows_j.append(cnt)
    rows_all = []
    for n in common:
        g = g_by_no[n]
        cnt = [0, 0, 0]
        ok = True
        for r in PRIMARY_RATERS:
            cnt[CAT_IDX[per_user[r][n]]] += 1
        for _, jk in JUDGES:
            v = g["per_provider_winners"].get(jk)
            if v is None:
                ok = False
                break
            cnt[CAT_IDX[v]] += 1
        if ok:
            rows_all.append(cnt)
    return {
        "n_common": len(common),
        "fleiss_humans": fleiss_kappa(rows_h, CATS3),
        "fleiss_judges": fleiss_kappa(rows_j, CATS3),
        "fleiss_humans_plus_judges": fleiss_kappa(rows_all, CATS3),
    }


def human_majority_vs_ensemble(per_user: dict, g_by_no: dict) -> dict:
    common = sorted(set.intersection(*[set(per_user[r]) for r in PRIMARY_RATERS]))
    pairs = []
    by_strat: dict[str, list] = defaultdict(list)
    by_axis: dict[str, list] = defaultdict(list)
    by_axis_pole: dict[tuple, list] = defaultdict(list)
    for n in common:
        g = g_by_no[n]
        hm = majority([per_user[r][n] for r in PRIMARY_RATERS])
        ev = g["judge_winner"]
        pairs.append((hm, ev))
        by_strat[g["stratum"]].append((hm, ev))
        by_axis[g["axis"]].append((hm, ev))
        by_axis_pole[(g["axis"], g["target_pole"])].append((hm, ev))
    k, a = cohen_kappa(pairs, CATS3)
    out = {
        "n": len(pairs),
        "kappa_overall": k,
        "agreement_overall": a,
        "by_stratum": {},
        "by_axis": {},
        "by_axis_pole": {},
    }
    for s in ["easy", "stress", "near_tie"]:
        ps = by_strat.get(s, [])
        kk, aa = cohen_kappa(ps, CATS3)
        out["by_stratum"][s] = {"n": len(ps), "kappa": kk, "agreement": aa}
    for ax in sorted(by_axis):
        ps = by_axis[ax]
        kk, aa = cohen_kappa(ps, CATS3)
        out["by_axis"][ax] = {"n": len(ps), "kappa": kk, "agreement": aa}
    for (ax, pol), ps in sorted(by_axis_pole.items()):
        kk, aa = cohen_kappa(ps, CATS3)
        out["by_axis_pole"][f"{ax}/{pol}"] = {
            "n": len(ps),
            "kappa": kk,
            "agreement": aa,
        }
    return out


def human_majority_win_rates(per_user: dict, g_by_no: dict) -> dict:
    """Compute substantive human-majority vote distribution (steered/base/tie).

    Returns counts and percentages overall and sliced by stratum and axis.
    """
    common = sorted(set.intersection(*[set(per_user[r]) for r in PRIMARY_RATERS]))

    def _dist(items: list[str]) -> dict:
        c = Counter(items)
        n = len(items)
        return {
            "n": n,
            "steered": c.get("steered", 0),
            "base": c.get("base", 0),
            "tie": c.get("tie", 0),
            "pct_steered": round(100 * c.get("steered", 0) / n, 1) if n else 0,
            "pct_base": round(100 * c.get("base", 0) / n, 1) if n else 0,
            "pct_tie": round(100 * c.get("tie", 0) / n, 1) if n else 0,
        }

    all_votes = []
    by_strat: dict[str, list[str]] = defaultdict(list)
    by_axis: dict[str, list[str]] = defaultdict(list)
    for n in common:
        g = g_by_no[n]
        hm = majority([per_user[r][n] for r in PRIMARY_RATERS])
        all_votes.append(hm)
        by_strat[g["stratum"]].append(hm)
        by_axis[g["axis"]].append(hm)

    out: dict = {"overall": _dist(all_votes)}
    out["by_stratum"] = {s: _dist(by_strat.get(s, [])) for s in ["easy", "stress", "near_tie"]}
    out["by_axis"] = {ax: _dist(by_axis[ax]) for ax in sorted(by_axis)}
    return out


def write_winrate_macros(wr: dict) -> str:
    """Generate a LaTeX macro file from win-rate results."""
    o = wr["overall"]
    e = wr["by_stratum"]["easy"]
    lines = [
        TABLE_HEADER,
        f"\\newcommand{{\\hmNtotal}}{{{o['n']}}}",
        f"\\newcommand{{\\hmSteered}}{{{o['steered']}}}",
        f"\\newcommand{{\\hmBase}}{{{o['base']}}}",
        f"\\newcommand{{\\hmTie}}{{{o['tie']}}}",
        f"\\newcommand{{\\hmPctSteered}}{{{int(round(o['pct_steered']))}}}",
        f"\\newcommand{{\\hmPctBase}}{{{int(round(o['pct_base']))}}}",
        f"\\newcommand{{\\hmPctTie}}{{{int(round(o['pct_tie']))}}}",
        f"\\newcommand{{\\hmEasyN}}{{{e['n']}}}",
        f"\\newcommand{{\\hmEasyPctSteered}}{{{int(round(e['pct_steered']))}}}",
        f"\\newcommand{{\\hmEasyPctBase}}{{{int(round(e['pct_base']))}}}",
        f"\\newcommand{{\\hmEasyPctTie}}{{{int(round(e['pct_tie']))}}}",
    ]
    for ax in sorted(wr["by_axis"]):
        d = wr["by_axis"][ax]
        tag = ax.capitalize()
        lines.append(f"\\newcommand{{\\hm{tag}N}}{{{d['n']}}}")
        lines.append(f"\\newcommand{{\\hm{tag}PctSteered}}{{{int(round(d['pct_steered']))}}}")
    return "\n".join(lines) + "\n"


def write_winrate_table_body(wr: dict, g_by_no: dict, common: list[int]) -> str:
    """Generate the \\input-able body rows for the human-vs-judge win-rate table."""
    # Compute judge distribution on same items
    judge_by: dict[str, Counter] = defaultdict(Counter)
    judge_all: Counter = Counter()
    for n in common:
        g = g_by_no[n]
        jw = g["judge_winner"]
        judge_all[jw] += 1
        judge_by[g["stratum"]][jw] += 1
        judge_by[g["axis"]][jw] += 1

    def _row(label: str, hd: dict, jc: Counter) -> str:
        n = hd["n"]
        jp = lambda k: int(round(100 * jc.get(k, 0) / n)) if n else 0
        return (
            f"{label} & {int(round(hd['pct_steered']))} & {int(round(hd['pct_base']))} "
            f"& {int(round(hd['pct_tie']))} & {jp('steered')} & {jp('base')} & {jp('tie')} \\\\"
        )

    rows = [_row(f"Overall ($n{{=}}{wr['overall']['n']}$)", wr["overall"], judge_all)]
    rows.append("\\midrule")
    for s in ["easy", "stress", "near_tie"]:
        label = s.replace("_", r"\_")
        rows.append(_row(f"\\quad {label}", wr["by_stratum"][s], judge_by[s]))
    rows.append("\\midrule")
    for ax in sorted(wr["by_axis"]):
        rows.append(_row(f"\\quad {ax}", wr["by_axis"][ax], judge_by[ax]))
    return TABLE_HEADER + "\n".join(rows) + "\n"


def per_rater_per_stratum(per_user: dict, g_by_no: dict) -> dict:
    out: dict[str, dict] = {}
    for r in PRIMARY_RATERS:
        items = per_user[r]
        row = {}
        for s in ["easy", "stress", "near_tie"]:
            pairs = []
            for n, h in items.items():
                g = g_by_no[n]
                if g["stratum"] != s:
                    continue
                pairs.append((h, g["judge_winner"]))
            k, a = cohen_kappa(pairs, CATS3)
            row[s] = {"n": len(pairs), "kappa": k, "agreement": a}
        out[r] = row
    return out


def per_rater_per_axis(per_user: dict, g_by_no: dict) -> dict:
    out: dict[str, dict] = {}
    for r in PRIMARY_RATERS:
        items = per_user[r]
        by_axis: dict[str, list] = defaultdict(list)
        for n, h in items.items():
            g = g_by_no[n]
            by_axis[g["axis"]].append((h, g["judge_winner"]))
        row = {}
        for ax in sorted(by_axis):
            k, a = cohen_kappa(by_axis[ax], CATS3)
            row[ax] = {"n": len(by_axis[ax]), "kappa": k, "agreement": a}
        out[r] = row
    return out


def per_rater_per_nagree(per_user: dict, g_by_no: dict) -> dict:
    out: dict[str, dict] = {}
    for r in PRIMARY_RATERS:
        items = per_user[r]
        row = {}
        for na in [3, 2, 1]:
            pairs = []
            for n, h in items.items():
                g = g_by_no[n]
                if g["n_agree"] != na:
                    continue
                pairs.append((h, g["judge_winner"]))
            k, a = cohen_kappa(pairs, CATS3)
            row[str(na)] = {"n": len(pairs), "kappa": k, "agreement": a}
        out[r] = row
    return out


# ----------------------------------------------------------------------------- table writers
def _fmt(v: float, places: int = 2) -> str:
    if v != v:  # NaN
        return "—"
    return f"${v:.{places}f}$"


def write_headline_table(summary: dict, fleiss: dict, hm: dict) -> str:
    rows = []
    pr = summary["per_rater_vs_ensemble"]
    for r in PRIMARY_RATERS:
        d = pr[r]
        rows.append(
            (
                anon(r),
                f"${d['n']}$",
                _fmt(d["kappa_vs_ensemble"]),
                _fmt(d["pearson_r_vs_delta_aa"]),
            )
        )
    # human-majority row + stratum subrows
    rows.append(
        (
            "Human-maj.\\ (joint)",
            f"${hm['n']}$",
            _fmt(hm["kappa_overall"]),
            "—",
        )
    )
    for s in ["easy", "stress", "near_tie"]:
        d = hm["by_stratum"][s]
        rows.append(
            (
                f"\\hspace{{1em}}$\\hookrightarrow$ {s.replace('_', r' ')}",
                f"${d['n']}$",
                _fmt(d["kappa"]),
                "—",
            )
        )
    body = "\n".join(f"{a} & {b} & {c} & {d} \\\\" for (a, b, c, d) in rows)
    fleiss_h = _fmt(fleiss["fleiss_humans"])
    fleiss_j = _fmt(fleiss["fleiss_judges"])
    return (
        TABLE_HEADER
        + r"""\begin{table}[t]\centering\scriptsize
\setlength{\tabcolsep}{3pt}
\begin{tabular}{@{}lccc@{}}
\toprule
\textbf{Rater / aggregate} & \textbf{$n$} & \textbf{$\kappa$ vs.\ Ens.} & \textbf{Pearson $r$ vs.\ $\Delta_\text{aa}$} \\
\midrule
"""
        + body
        + "\n\\midrule\n"
        + f"Fleiss $\\kappa$ humans (n={fleiss['n_common']}) & & {fleiss_h} & — \\\\\n"
        + f"Fleiss $\\kappa$ judges (n={fleiss['n_common']}) & & {fleiss_j} & — \\\\\n"
        + r"""\bottomrule
\end{tabular}
\caption{Inter-rater reliability headline. Cohen's $\kappa$ on 3-category
(base/steered/tie) winner labels against the 3-provider ensemble winner.
Human-majority breakdown by ensemble-sample stratum (easy: clear ensemble
winner; near\_tie: ensemble uncertainty by design). Pearson $r$ is computed
on the continuous ensemble $\Delta_\text{axis-alignment}$ vs.\ human winner
coded as $\pm 1/0$.}
\label{tab:irr-headline}
\end{table}
"""
    )


def write_stratum_table(summary: dict, fleiss: dict) -> str:
    hm = summary["human_majority_vs_ensemble"]
    # also inter-human Fleiss per stratum and inter-judge Fleiss per stratum
    per_strat = summary["fleiss_per_stratum"]
    rows = []
    for s in ["easy", "stress", "near_tie"]:
        d = hm["by_stratum"][s]
        fh = per_strat[s]["fleiss_humans"]
        fj = per_strat[s]["fleiss_judges"]
        rows.append(
            (
                s.replace("_", r"\_"),
                f"${d['n']}$",
                _fmt(fh),
                _fmt(d["kappa"]),
                _fmt(fj),
            )
        )
    rows.append(
        (
            "overall",
            f"${hm['n']}$",
            _fmt(fleiss["fleiss_humans"]),
            _fmt(hm["kappa_overall"]),
            _fmt(fleiss["fleiss_judges"]),
        )
    )
    body = "\n".join(
        f"{a} & {b} & {c} & {d} & {e} \\\\" for (a, b, c, d, e) in rows
    )
    return (
        TABLE_HEADER
        + r"""\begin{table}[t]\centering\scriptsize
\setlength{\tabcolsep}{3pt}
\begin{tabular}{@{}lcccc@{}}
\toprule
\textbf{Stratum} & \textbf{$n$} & \textbf{$\kappa_\text{Fl.}$ hum.} & \textbf{HM--Ens.\ $\kappa$} & \textbf{$\kappa_\text{Fl.}$ judg.} \\
\midrule
"""
        + body
        + r"""
\bottomrule
\end{tabular}
\caption{Per-stratum reliability. ``HM vs.\ Ens.'' is Cohen's $\kappa$
between the human-majority label and the ensemble label on the
$n{=}""" + str(hm["n"]) + r"""$ all-rater overlap. Easy items (clear ensemble winners,
$|\Delta_\text{aa}|\geq 2$, all judges agree on a non-tie winner)
reach near-perfect agreement; the Fleiss $\kappa{=}1.0$ for judges on
the easy stratum is the sampler's stratum definition (all 3 judges
must agree on a non-tie winner). Near\_tie items were selected for
ensemble uncertainty and remain ambiguous under human inspection.}
\label{tab:irr-stratum}
\end{table}
"""
    )


def write_axis_table(summary: dict) -> str:
    hm = summary["human_majority_vs_ensemble"]
    per_axis = summary["fleiss_per_axis"]
    rows = []
    for ax in sorted(hm["by_axis"]):
        d = hm["by_axis"][ax]
        fh = per_axis[ax]["fleiss_humans"]
        rows.append(
            (
                ax,
                f"${d['n']}$",
                _fmt(fh),
                _fmt(d["kappa"]),
            )
        )
    body = "\n".join(f"{a} & {b} & {c} & {d} \\\\" for (a, b, c, d) in rows)
    return (
        TABLE_HEADER
        + r"""\begin{table}[t]\centering\scriptsize
\setlength{\tabcolsep}{3pt}
\begin{tabular}{@{}lccc@{}}
\toprule
\textbf{Axis} & \textbf{$n$} & \textbf{Fleiss $\kappa$ humans} & \textbf{Cohen $\kappa$ HM vs.\ Ens.} \\
\midrule
"""
        + body
        + r"""
\bottomrule
\end{tabular}
\caption{Per-axis reliability on the $n{=}""" + str(hm["n"]) + r"""$ all-rater overlap.
Per axis $\times$ pole ($n$ per cell 11--16), point estimates only —
confidence intervals are wide and reported in
\texttt{outputs/human\_eval/v3/irr\_summary.json}. The
$\kappa$-paradox can occur on highly skewed marginals (e.g.\
\texttt{cooperation/negative}); see appendix discussion.}
\label{tab:irr-axis}
\end{table}
"""
    )


def write_nagree_table(summary: dict) -> str:
    rows_per_rater = summary["per_rater_per_nagree"]
    n_raters = len(PRIMARY_RATERS)
    rows = []
    for na in ["3", "2", "1"]:
        n_items = "—"
        cells = []
        for r in PRIMARY_RATERS:
            cell = rows_per_rater[r].get(na, {})
            cells.append(_fmt(cell.get("kappa", float("nan"))))
            if n_items == "—" and cell.get("n", 0) > 0:
                n_items = f"${cell['n']}$"
        rows.append((na, n_items, *cells))
    body = "\n".join(
        "$" + a + "$ & " + " & ".join(parts) + " \\\\"
        for (a, *parts) in rows
    )
    col_spec = "@{}l" + "c" * (n_raters + 1) + "@{}"
    rater_headers = " & ".join(
        f"\\textbf{{Rater {i+1}}}" for i in range(n_raters)
    )
    return (
        TABLE_HEADER
        + r"\begin{table}[t]\centering\scriptsize" + "\n"
        + r"\setlength{\tabcolsep}{3pt}" + "\n"
        + r"\begin{tabular}{" + col_spec + "}\n"
        + r"\toprule" + "\n"
        + r"\textbf{$n_\text{agree}$} & \textbf{$n$} & " + rater_headers + r" \\" + "\n"
        + r"\midrule" + "\n"
        + body
        + r"""
\bottomrule
\end{tabular}
\caption{Cohen's $\kappa$ vs.\ ensemble winner, partitioned by
\texttt{n\_agree} (number of judges that vote the ensemble winner).
On items with unanimous judges ($n_\text{agree}{=}3$) every human
rater reaches moderate-to-substantial agreement; on split-judge
items ($n_\text{agree}{=}2$) agreement collapses to chance. The
$n_\text{agree}{=}1$ row contains a single item and is not
analysable. This quantitatively justifies the use of
\texttt{n\_agree}${=}3$ as the high-confidence filter in headline
matrices (\S5).}
\label{tab:irr-nagree}
\end{table}
"""
    )


# ----------------------------------------------------------------------------- per-stratum/axis Fleiss helpers
def fleiss_per_partition(
    per_user: dict, g_by_no: dict, key_fn
) -> dict[str, dict[str, float]]:
    """Compute Fleiss humans + judges per partition (e.g. stratum or axis)."""
    common = sorted(set.intersection(*[set(per_user[r]) for r in PRIMARY_RATERS]))
    buckets: dict[str, list[int]] = defaultdict(list)
    for n in common:
        buckets[key_fn(g_by_no[n])].append(n)
    out = {}
    for key, ns in buckets.items():
        rows_h = []
        rows_j = []
        for n in ns:
            cnt_h = [0, 0, 0]
            for r in PRIMARY_RATERS:
                cnt_h[CAT_IDX[per_user[r][n]]] += 1
            rows_h.append(cnt_h)
            g = g_by_no[n]
            cnt_j = [0, 0, 0]
            ok = True
            for _, jk in JUDGES:
                v = g["per_provider_winners"].get(jk)
                if v is None:
                    ok = False
                    break
                cnt_j[CAT_IDX[v]] += 1
            if ok:
                rows_j.append(cnt_j)
        out[key] = {
            "n": len(ns),
            "fleiss_humans": fleiss_kappa(rows_h, CATS3),
            "fleiss_judges": fleiss_kappa(rows_j, CATS3),
        }
    return out


# ----------------------------------------------------------------------------- main
def main() -> None:
    g_by_no, per_user = load_data()

    # Record raw coverage including dropped raters
    coverage = {u: len(d) for u, d in per_user.items()}
    dropped = {u: n for u, n in coverage.items() if u not in PRIMARY_RATERS}

    # Restrict per_user dict to PRIMARY_RATERS for downstream calcs
    pu = {r: per_user[r] for r in PRIMARY_RATERS}

    rater_vs_ens = per_rater_vs_ensemble(pu, g_by_no)
    rater_vs_judges = per_rater_vs_each_judge(pu, g_by_no)
    inter_h = inter_human_pairwise(pu)
    fleiss_block_out = fleiss_block(pu, g_by_no)
    hm = human_majority_vs_ensemble(pu, g_by_no)
    per_strat = per_rater_per_stratum(pu, g_by_no)
    per_axis = per_rater_per_axis(pu, g_by_no)
    per_nagree = per_rater_per_nagree(pu, g_by_no)
    fl_per_strat = fleiss_per_partition(pu, g_by_no, lambda g: g["stratum"])
    fl_per_axis = fleiss_per_partition(pu, g_by_no, lambda g: g["axis"])
    wr = human_majority_win_rates(pu, g_by_no)

    summary = {
        "n_sample_items": len(g_by_no),
        "coverage": coverage,
        "dropped_raters": dropped,
        "primary_raters": PRIMARY_RATERS,
        "per_rater_vs_ensemble": rater_vs_ens,
        "per_rater_vs_each_judge": rater_vs_judges,
        "inter_human_pairwise": inter_h,
        "fleiss": fleiss_block_out,
        "human_majority_vs_ensemble": hm,
        "per_rater_per_stratum": per_strat,
        "per_rater_per_axis": per_axis,
        "per_rater_per_nagree": per_nagree,
        "fleiss_per_stratum": fl_per_strat,
        "fleiss_per_axis": fl_per_axis,
        "human_majority_win_rates": wr,
    }
    SUMMARY_PATH.parent.mkdir(parents=True, exist_ok=True)
    with SUMMARY_PATH.open("w") as f:
        json.dump(summary, f, indent=2, sort_keys=True)
    print(f"Wrote {SUMMARY_PATH.relative_to(ROOT)}")

    TABLES_DIR.mkdir(parents=True, exist_ok=True)
    for fname, content in [
        ("tab_irr_headline.tex", write_headline_table(summary, fleiss_block_out, hm)),
        ("tab_irr_stratum.tex", write_stratum_table(summary, fleiss_block_out)),
        ("tab_irr_axis.tex", write_axis_table(summary)),
        ("tab_irr_nagree.tex", write_nagree_table(summary)),
        ("irr_winrate_macros.tex", write_winrate_macros(wr)),
        ("tab_irr_winrate_body.tex", write_winrate_table_body(
            wr, g_by_no,
            sorted(set.intersection(*[set(pu[r]) for r in PRIMARY_RATERS])))),
    ]:
        path = TABLES_DIR / fname
        path.write_text(content)
        print(f"Wrote {path.relative_to(ROOT)}")

    # Print a concise console headline
    print("\n=== IRR headline ===")
    print(
        f"Fleiss κ humans (n={fleiss_block_out['n_common']}) = "
        f"{fleiss_block_out['fleiss_humans']:.3f}"
    )
    print(
        f"Fleiss κ judges (n={fleiss_block_out['n_common']}) = "
        f"{fleiss_block_out['fleiss_judges']:.3f}"
    )
    print(f"Human-majority vs ensemble overall κ = {hm['kappa_overall']:.3f}")
    for s in ["easy", "stress", "near_tie"]:
        d = hm["by_stratum"][s]
        print(f"  {s}: n={d['n']}  κ={d['kappa']:.3f}")

    print("\n=== Human-majority win rates ===")
    o = wr["overall"]
    print(f"Overall (n={o['n']}): {o['pct_steered']}% steered, {o['pct_base']}% base, {o['pct_tie']}% tie")
    for s in ["easy", "stress", "near_tie"]:
        d = wr["by_stratum"][s]
        print(f"  {s} (n={d['n']}): {d['pct_steered']}% steered, {d['pct_base']}% base, {d['pct_tie']}% tie")
    for ax in sorted(wr["by_axis"]):
        d = wr["by_axis"][ax]
        print(f"  {ax} (n={d['n']}): {d['pct_steered']}% steered, {d['pct_base']}% base, {d['pct_tie']}% tie")


if __name__ == "__main__":
    main()
