cluster_name: cluster_a
slurm:
  partition: p4
  qos: gpubasic
  time: "48:00:00"
  nodes: 1
  ntasks: 1
  cpus_per_task: 6
  mem: 64G
  gres: gpu:1
  mail_type: END
  mail_user: anon@example.com
  modules:
    - cuda/cuda-12.6
    - python/python-3.13.0
  env_file: .env
  venv_activate: $ENV_DIR/bin/activate
